// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArFznjMFAvXTgdJxhcGDsb94Y-TsKIGZg',
    appId: '1:466286160074:web:bd5aba8a7b662efb816c33',
    messagingSenderId: '466286160074',
    projectId: 'stockmarketapp-dffca',
    authDomain: 'stockmarketapp-dffca.firebaseapp.com',
    storageBucket: 'stockmarketapp-dffca.firebasestorage.app',
    measurementId: 'G-DFFJV8ZEE6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDae1ZtvX7rWGFaFXYeRQcWa1nCNwChBFw',
    appId: '1:466286160074:android:9166e3a8e4793f6c816c33',
    messagingSenderId: '466286160074',
    projectId: 'stockmarketapp-dffca',
    storageBucket: 'stockmarketapp-dffca.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCS1vBdD2KgYPMOW5zj5lXWMCDBATyAFng',
    appId: '1:466286160074:ios:2019a8772e739028816c33',
    messagingSenderId: '466286160074',
    projectId: 'stockmarketapp-dffca',
    storageBucket: 'stockmarketapp-dffca.firebasestorage.app',
    iosBundleId: 'com.example.dhanapi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCS1vBdD2KgYPMOW5zj5lXWMCDBATyAFng',
    appId: '1:466286160074:ios:2019a8772e739028816c33',
    messagingSenderId: '466286160074',
    projectId: 'stockmarketapp-dffca',
    storageBucket: 'stockmarketapp-dffca.firebasestorage.app',
    iosBundleId: 'com.example.dhanapi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyArFznjMFAvXTgdJxhcGDsb94Y-TsKIGZg',
    appId: '1:466286160074:web:6038ac791f387ce9816c33',
    messagingSenderId: '466286160074',
    projectId: 'stockmarketapp-dffca',
    authDomain: 'stockmarketapp-dffca.firebaseapp.com',
    storageBucket: 'stockmarketapp-dffca.firebasestorage.app',
    measurementId: 'G-1BTHKGBTQ7',
  );
}
